// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CommonMessageProtoMsg.proto

package com.road.arpg.module.misc.protobuff;

public final class CommonMessageProto {
    private CommonMessageProto() {
    }

    public static void registerAllExtensions(
                    com.google.protobuf.ExtensionRegistry registry) {
    }

    public interface CommonMessageProtoMsgOrBuilder extends
                    com.google.protobuf.MessageOrBuilder {

        // required int32 type = 1;
        boolean hasType();

        int getType();

        // required string content = 2;
        boolean hasContent();

        String getContent();
    }

    public static final class CommonMessageProtoMsg extends
                    com.google.protobuf.GeneratedMessage implements
                    CommonMessageProtoMsgOrBuilder {
        // Use CommonMessageProtoMsg.newBuilder() to construct.
        private CommonMessageProtoMsg(Builder builder) {
            super(builder);
        }

        private CommonMessageProtoMsg(boolean noInit) {
        }

        private static final CommonMessageProtoMsg defaultInstance;

        public static CommonMessageProtoMsg getDefaultInstance() {
            return defaultInstance;
        }

        public CommonMessageProtoMsg getDefaultInstanceForType() {
            return defaultInstance;
        }

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return com.road.arpg.module.misc.protobuff.CommonMessageProto.internal_static_com_road_arpg_module_common_command_proto_CommonMessageProtoMsg_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
            return com.road.arpg.module.misc.protobuff.CommonMessageProto.internal_static_com_road_arpg_module_common_command_proto_CommonMessageProtoMsg_fieldAccessorTable;
        }

        private int bitField0_;
        // required int32 type = 1;
        public static final int TYPE_FIELD_NUMBER = 1;
        private int type_;

        public boolean hasType() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        public int getType() {
            return type_;
        }

        // required string content = 2;
        public static final int CONTENT_FIELD_NUMBER = 2;
        private java.lang.Object content_;

        public boolean hasContent() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        public String getContent() {
            java.lang.Object ref = content_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (com.google.protobuf.Internal.isValidUtf8(bs)) {
                    content_ = s;
                }
                return s;
            }
        }

        private com.google.protobuf.ByteString getContentBytes() {
            java.lang.Object ref = content_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString
                                .copyFromUtf8((String) ref);
                content_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private void initFields() {
            type_ = 0;
            content_ = "";
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized != -1)
                return isInitialized == 1;

            if (!hasType()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasContent()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeInt32(1, type_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeBytes(2, getContentBytes());
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1)
                return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream.computeInt32Size(
                                1, type_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream.computeBytesSize(
                                2, getContentBytes());
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @java.lang.Override
        protected java.lang.Object writeReplace()
                        throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static com.road.arpg.module.misc.protobuff.CommonMessageProto.CommonMessageProtoMsg parseFrom(
                        com.google.protobuf.ByteString data)
                        throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }

        public static com.road.arpg.module.misc.protobuff.CommonMessageProto.CommonMessageProtoMsg parseFrom(
                        com.google.protobuf.ByteString data,
                        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                            .buildParsed();
        }

        public static com.road.arpg.module.misc.protobuff.CommonMessageProto.CommonMessageProtoMsg parseFrom(
                        byte[] data)
                        throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }

        public static com.road.arpg.module.misc.protobuff.CommonMessageProto.CommonMessageProtoMsg parseFrom(
                        byte[] data,
                        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                            .buildParsed();
        }

        public static com.road.arpg.module.misc.protobuff.CommonMessageProto.CommonMessageProtoMsg parseFrom(
                        java.io.InputStream input) throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }

        public static com.road.arpg.module.misc.protobuff.CommonMessageProto.CommonMessageProtoMsg parseFrom(
                        java.io.InputStream input,
                        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                            .buildParsed();
        }

        public static com.road.arpg.module.misc.protobuff.CommonMessageProto.CommonMessageProtoMsg parseDelimitedFrom(
                        java.io.InputStream input) throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }

        public static com.road.arpg.module.misc.protobuff.CommonMessageProto.CommonMessageProtoMsg parseDelimitedFrom(
                        java.io.InputStream input,
                        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }

        public static com.road.arpg.module.misc.protobuff.CommonMessageProto.CommonMessageProtoMsg parseFrom(
                        com.google.protobuf.CodedInputStream input)
                        throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }

        public static com.road.arpg.module.misc.protobuff.CommonMessageProto.CommonMessageProtoMsg parseFrom(
                        com.google.protobuf.CodedInputStream input,
                        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                            .buildParsed();
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(
                        com.road.arpg.module.misc.protobuff.CommonMessageProto.CommonMessageProtoMsg prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        public static final class Builder extends
                        com.google.protobuf.GeneratedMessage.Builder<Builder>
                        implements
                        com.road.arpg.module.misc.protobuff.CommonMessageProto.CommonMessageProtoMsgOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return com.road.arpg.module.misc.protobuff.CommonMessageProto.internal_static_com_road_arpg_module_common_command_proto_CommonMessageProtoMsg_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
                return com.road.arpg.module.misc.protobuff.CommonMessageProto.internal_static_com_road_arpg_module_common_command_proto_CommonMessageProtoMsg_fieldAccessorTable;
            }

            // Construct using com.road.arpg.module.common.protobuff.CommonMessageProto.CommonMessageProtoMsg.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                type_ = 0;
                bitField0_ = (bitField0_ & ~0x00000001);
                content_ = "";
                bitField0_ = (bitField0_ & ~0x00000002);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                return com.road.arpg.module.misc.protobuff.CommonMessageProto.CommonMessageProtoMsg
                                .getDescriptor();
            }

            public com.road.arpg.module.misc.protobuff.CommonMessageProto.CommonMessageProtoMsg getDefaultInstanceForType() {
                return com.road.arpg.module.misc.protobuff.CommonMessageProto.CommonMessageProtoMsg
                                .getDefaultInstance();
            }

            public com.road.arpg.module.misc.protobuff.CommonMessageProto.CommonMessageProtoMsg build() {
                com.road.arpg.module.misc.protobuff.CommonMessageProto.CommonMessageProtoMsg result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            private com.road.arpg.module.misc.protobuff.CommonMessageProto.CommonMessageProtoMsg buildParsed()
                            throws com.google.protobuf.InvalidProtocolBufferException {
                com.road.arpg.module.misc.protobuff.CommonMessageProto.CommonMessageProtoMsg result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result)
                                    .asInvalidProtocolBufferException();
                }
                return result;
            }

            public com.road.arpg.module.misc.protobuff.CommonMessageProto.CommonMessageProtoMsg buildPartial() {
                com.road.arpg.module.misc.protobuff.CommonMessageProto.CommonMessageProtoMsg result = new com.road.arpg.module.misc.protobuff.CommonMessageProto.CommonMessageProtoMsg(
                                this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.type_ = type_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.content_ = content_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.road.arpg.module.misc.protobuff.CommonMessageProto.CommonMessageProtoMsg) {
                    return mergeFrom((com.road.arpg.module.misc.protobuff.CommonMessageProto.CommonMessageProtoMsg) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(
                            com.road.arpg.module.misc.protobuff.CommonMessageProto.CommonMessageProtoMsg other) {
                if (other == com.road.arpg.module.misc.protobuff.CommonMessageProto.CommonMessageProtoMsg
                                .getDefaultInstance())
                    return this;
                if (other.hasType()) {
                    setType(other.getType());
                }
                if (other.hasContent()) {
                    setContent(other.getContent());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                if (!hasType()) {

                    return false;
                }
                if (!hasContent()) {

                    return false;
                }
                return true;
            }

            public Builder mergeFrom(
                            com.google.protobuf.CodedInputStream input,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws java.io.IOException {
                com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
                                .newBuilder(this.getUnknownFields());
                while (true) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            this.setUnknownFields(unknownFields.build());
                            onChanged();
                            return this;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                            extensionRegistry, tag)) {
                                this.setUnknownFields(unknownFields.build());
                                onChanged();
                                return this;
                            }
                            break;
                        }
                        case 8: {
                            bitField0_ |= 0x00000001;
                            type_ = input.readInt32();
                            break;
                        }
                        case 18: {
                            bitField0_ |= 0x00000002;
                            content_ = input.readBytes();
                            break;
                        }
                    }
                }
            }

            private int bitField0_;

            // required int32 type = 1;
            private int type_;

            public boolean hasType() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            public int getType() {
                return type_;
            }

            public Builder setType(int value) {
                bitField0_ |= 0x00000001;
                type_ = value;
                onChanged();
                return this;
            }

            public Builder clearType() {
                bitField0_ = (bitField0_ & ~0x00000001);
                type_ = 0;
                onChanged();
                return this;
            }

            // required string content = 2;
            private java.lang.Object content_ = "";

            public boolean hasContent() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            public String getContent() {
                java.lang.Object ref = content_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref)
                                    .toStringUtf8();
                    content_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            public Builder setContent(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                content_ = value;
                onChanged();
                return this;
            }

            public Builder clearContent() {
                bitField0_ = (bitField0_ & ~0x00000002);
                content_ = getDefaultInstance().getContent();
                onChanged();
                return this;
            }

            void setContent(com.google.protobuf.ByteString value) {
                bitField0_ |= 0x00000002;
                content_ = value;
                onChanged();
            }

            // @@protoc_insertion_point(builder_scope:com.road.arpg.module.common.command.proto.CommonMessageProtoMsg)
        }

        static {
            defaultInstance = new CommonMessageProtoMsg(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:com.road.arpg.module.common.command.proto.CommonMessageProtoMsg)
    }

    private static com.google.protobuf.Descriptors.Descriptor internal_static_com_road_arpg_module_common_command_proto_CommonMessageProtoMsg_descriptor;
    private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_com_road_arpg_module_common_command_proto_CommonMessageProtoMsg_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
    static {
        java.lang.String[] descriptorData = { "\n\033CommonMessageProtoMsg.proto\022)com.road."
                        + "arpg.module.common.command.proto\"6\n\025Comm"
                        + "onMessageProtoMsg\022\014\n\004type\030\001 \002(\005\022\017\n\007conte"
                        + "nt\030\002 \002(\tB<\n&com.road.arpg.module.common."
                        + "command.pbB\022CommonMessageProto" };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
            public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                descriptor = root;
                internal_static_com_road_arpg_module_common_command_proto_CommonMessageProtoMsg_descriptor = getDescriptor()
                                .getMessageTypes().get(0);
                internal_static_com_road_arpg_module_common_command_proto_CommonMessageProtoMsg_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                                internal_static_com_road_arpg_module_common_command_proto_CommonMessageProtoMsg_descriptor,
                                new java.lang.String[] { "Type", "Content", },
                                com.road.arpg.module.misc.protobuff.CommonMessageProto.CommonMessageProtoMsg.class,
                                com.road.arpg.module.misc.protobuff.CommonMessageProto.CommonMessageProtoMsg.Builder.class);
                return null;
            }
        };
        com.google.protobuf.Descriptors.FileDescriptor
                        .internalBuildGeneratedFileFrom(
                                        descriptorData,
                                        new com.google.protobuf.Descriptors.FileDescriptor[] {},
                                        assigner);
    }

    // @@protoc_insertion_point(outer_class_scope)
}
