// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LoginProtoMsg.proto

package com.road.arpg.module.misc.protobuff;

public final class LoginProto {
    private LoginProto() {
    }

    public static void registerAllExtensions(
                    com.google.protobuf.ExtensionRegistry registry) {
    }

    public interface LoginProtoMsgOrBuilder extends
                    com.google.protobuf.MessageOrBuilder {

        // required string username = 1;
        boolean hasUsername();

        String getUsername();

        // required string site = 2;
        boolean hasSite();

        String getSite();
    }

    public static final class LoginProtoMsg extends
                    com.google.protobuf.GeneratedMessage implements
                    LoginProtoMsgOrBuilder {
        // Use LoginProtoMsg.newBuilder() to construct.
        private LoginProtoMsg(Builder builder) {
            super(builder);
        }

        private LoginProtoMsg(boolean noInit) {
        }

        private static final LoginProtoMsg defaultInstance;

        public static LoginProtoMsg getDefaultInstance() {
            return defaultInstance;
        }

        public LoginProtoMsg getDefaultInstanceForType() {
            return defaultInstance;
        }

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return com.road.arpg.module.misc.protobuff.LoginProto.internal_static_com_road_arpg_module_common_command_proto_LoginProtoMsg_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
            return com.road.arpg.module.misc.protobuff.LoginProto.internal_static_com_road_arpg_module_common_command_proto_LoginProtoMsg_fieldAccessorTable;
        }

        private int bitField0_;
        // required string username = 1;
        public static final int USERNAME_FIELD_NUMBER = 1;
        private java.lang.Object username_;

        public boolean hasUsername() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        public String getUsername() {
            java.lang.Object ref = username_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (com.google.protobuf.Internal.isValidUtf8(bs)) {
                    username_ = s;
                }
                return s;
            }
        }

        private com.google.protobuf.ByteString getUsernameBytes() {
            java.lang.Object ref = username_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString
                                .copyFromUtf8((String) ref);
                username_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        // required string site = 2;
        public static final int SITE_FIELD_NUMBER = 2;
        private java.lang.Object site_;

        public boolean hasSite() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        public String getSite() {
            java.lang.Object ref = site_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (com.google.protobuf.Internal.isValidUtf8(bs)) {
                    site_ = s;
                }
                return s;
            }
        }

        private com.google.protobuf.ByteString getSiteBytes() {
            java.lang.Object ref = site_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString
                                .copyFromUtf8((String) ref);
                site_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private void initFields() {
            username_ = "";
            site_ = "";
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized != -1)
                return isInitialized == 1;

            if (!hasUsername()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasSite()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeBytes(1, getUsernameBytes());
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeBytes(2, getSiteBytes());
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1)
                return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream.computeBytesSize(
                                1, getUsernameBytes());
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream.computeBytesSize(
                                2, getSiteBytes());
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @java.lang.Override
        protected java.lang.Object writeReplace()
                        throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static com.road.arpg.module.misc.protobuff.LoginProto.LoginProtoMsg parseFrom(
                        com.google.protobuf.ByteString data)
                        throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }

        public static com.road.arpg.module.misc.protobuff.LoginProto.LoginProtoMsg parseFrom(
                        com.google.protobuf.ByteString data,
                        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                            .buildParsed();
        }

        public static com.road.arpg.module.misc.protobuff.LoginProto.LoginProtoMsg parseFrom(
                        byte[] data)
                        throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }

        public static com.road.arpg.module.misc.protobuff.LoginProto.LoginProtoMsg parseFrom(
                        byte[] data,
                        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                            .buildParsed();
        }

        public static com.road.arpg.module.misc.protobuff.LoginProto.LoginProtoMsg parseFrom(
                        java.io.InputStream input) throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }

        public static com.road.arpg.module.misc.protobuff.LoginProto.LoginProtoMsg parseFrom(
                        java.io.InputStream input,
                        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                            .buildParsed();
        }

        public static com.road.arpg.module.misc.protobuff.LoginProto.LoginProtoMsg parseDelimitedFrom(
                        java.io.InputStream input) throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }

        public static com.road.arpg.module.misc.protobuff.LoginProto.LoginProtoMsg parseDelimitedFrom(
                        java.io.InputStream input,
                        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }

        public static com.road.arpg.module.misc.protobuff.LoginProto.LoginProtoMsg parseFrom(
                        com.google.protobuf.CodedInputStream input)
                        throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }

        public static com.road.arpg.module.misc.protobuff.LoginProto.LoginProtoMsg parseFrom(
                        com.google.protobuf.CodedInputStream input,
                        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                            .buildParsed();
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(
                        com.road.arpg.module.misc.protobuff.LoginProto.LoginProtoMsg prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        public static final class Builder extends
                        com.google.protobuf.GeneratedMessage.Builder<Builder>
                        implements
                        com.road.arpg.module.misc.protobuff.LoginProto.LoginProtoMsgOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return com.road.arpg.module.misc.protobuff.LoginProto.internal_static_com_road_arpg_module_common_command_proto_LoginProtoMsg_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
                return com.road.arpg.module.misc.protobuff.LoginProto.internal_static_com_road_arpg_module_common_command_proto_LoginProtoMsg_fieldAccessorTable;
            }

            // Construct using com.road.arpg.module.common.protobuff.LoginProto.LoginProtoMsg.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                username_ = "";
                bitField0_ = (bitField0_ & ~0x00000001);
                site_ = "";
                bitField0_ = (bitField0_ & ~0x00000002);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                return com.road.arpg.module.misc.protobuff.LoginProto.LoginProtoMsg
                                .getDescriptor();
            }

            public com.road.arpg.module.misc.protobuff.LoginProto.LoginProtoMsg getDefaultInstanceForType() {
                return com.road.arpg.module.misc.protobuff.LoginProto.LoginProtoMsg
                                .getDefaultInstance();
            }

            public com.road.arpg.module.misc.protobuff.LoginProto.LoginProtoMsg build() {
                com.road.arpg.module.misc.protobuff.LoginProto.LoginProtoMsg result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            private com.road.arpg.module.misc.protobuff.LoginProto.LoginProtoMsg buildParsed()
                            throws com.google.protobuf.InvalidProtocolBufferException {
                com.road.arpg.module.misc.protobuff.LoginProto.LoginProtoMsg result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result)
                                    .asInvalidProtocolBufferException();
                }
                return result;
            }

            public com.road.arpg.module.misc.protobuff.LoginProto.LoginProtoMsg buildPartial() {
                com.road.arpg.module.misc.protobuff.LoginProto.LoginProtoMsg result = new com.road.arpg.module.misc.protobuff.LoginProto.LoginProtoMsg(
                                this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.username_ = username_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.site_ = site_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.road.arpg.module.misc.protobuff.LoginProto.LoginProtoMsg) {
                    return mergeFrom((com.road.arpg.module.misc.protobuff.LoginProto.LoginProtoMsg) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(
                            com.road.arpg.module.misc.protobuff.LoginProto.LoginProtoMsg other) {
                if (other == com.road.arpg.module.misc.protobuff.LoginProto.LoginProtoMsg
                                .getDefaultInstance())
                    return this;
                if (other.hasUsername()) {
                    setUsername(other.getUsername());
                }
                if (other.hasSite()) {
                    setSite(other.getSite());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                if (!hasUsername()) {

                    return false;
                }
                if (!hasSite()) {

                    return false;
                }
                return true;
            }

            public Builder mergeFrom(
                            com.google.protobuf.CodedInputStream input,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws java.io.IOException {
                com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
                                .newBuilder(this.getUnknownFields());
                while (true) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            this.setUnknownFields(unknownFields.build());
                            onChanged();
                            return this;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                            extensionRegistry, tag)) {
                                this.setUnknownFields(unknownFields.build());
                                onChanged();
                                return this;
                            }
                            break;
                        }
                        case 10: {
                            bitField0_ |= 0x00000001;
                            username_ = input.readBytes();
                            break;
                        }
                        case 18: {
                            bitField0_ |= 0x00000002;
                            site_ = input.readBytes();
                            break;
                        }
                    }
                }
            }

            private int bitField0_;

            // required string username = 1;
            private java.lang.Object username_ = "";

            public boolean hasUsername() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            public String getUsername() {
                java.lang.Object ref = username_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref)
                                    .toStringUtf8();
                    username_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            public Builder setUsername(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                username_ = value;
                onChanged();
                return this;
            }

            public Builder clearUsername() {
                bitField0_ = (bitField0_ & ~0x00000001);
                username_ = getDefaultInstance().getUsername();
                onChanged();
                return this;
            }

            void setUsername(com.google.protobuf.ByteString value) {
                bitField0_ |= 0x00000001;
                username_ = value;
                onChanged();
            }

            // required string site = 2;
            private java.lang.Object site_ = "";

            public boolean hasSite() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            public String getSite() {
                java.lang.Object ref = site_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref)
                                    .toStringUtf8();
                    site_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            public Builder setSite(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                site_ = value;
                onChanged();
                return this;
            }

            public Builder clearSite() {
                bitField0_ = (bitField0_ & ~0x00000002);
                site_ = getDefaultInstance().getSite();
                onChanged();
                return this;
            }

            void setSite(com.google.protobuf.ByteString value) {
                bitField0_ |= 0x00000002;
                site_ = value;
                onChanged();
            }

            // @@protoc_insertion_point(builder_scope:com.road.arpg.module.common.command.proto.LoginProtoMsg)
        }

        static {
            defaultInstance = new LoginProtoMsg(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:com.road.arpg.module.common.command.proto.LoginProtoMsg)
    }

    private static com.google.protobuf.Descriptors.Descriptor internal_static_com_road_arpg_module_common_command_proto_LoginProtoMsg_descriptor;
    private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_com_road_arpg_module_common_command_proto_LoginProtoMsg_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
    static {
        java.lang.String[] descriptorData = { "\n\023LoginProtoMsg.proto\022)com.road.arpg.mod"
                        + "ule.common.command.proto\"/\n\rLoginProtoMs"
                        + "g\022\020\n\010username\030\001 \002(\t\022\014\n\004site\030\002 \002(\tB4\n&com"
                        + ".road.arpg.module.common.command.pbB\nLog"
                        + "inProto" };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
            public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                descriptor = root;
                internal_static_com_road_arpg_module_common_command_proto_LoginProtoMsg_descriptor = getDescriptor()
                                .getMessageTypes().get(0);
                internal_static_com_road_arpg_module_common_command_proto_LoginProtoMsg_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                                internal_static_com_road_arpg_module_common_command_proto_LoginProtoMsg_descriptor,
                                new java.lang.String[] { "Username", "Site", },
                                com.road.arpg.module.misc.protobuff.LoginProto.LoginProtoMsg.class,
                                com.road.arpg.module.misc.protobuff.LoginProto.LoginProtoMsg.Builder.class);
                return null;
            }
        };
        com.google.protobuf.Descriptors.FileDescriptor
                        .internalBuildGeneratedFileFrom(
                                        descriptorData,
                                        new com.google.protobuf.Descriptors.FileDescriptor[] {},
                                        assigner);
    }

    // @@protoc_insertion_point(outer_class_scope)
}
