// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LoginSuccessProtoMsg.proto

package com.road.arpg.module.misc.protobuff;

public final class LoginSuccessProto {
    private LoginSuccessProto() {
    }

    public static void registerAllExtensions(
                    com.google.protobuf.ExtensionRegistry registry) {
    }

    public interface LoginSuccessProtoMsgOrBuilder extends
                    com.google.protobuf.MessageOrBuilder {

        // required int64 playerID = 1;
        boolean hasPlayerID();

        long getPlayerID();
    }

    public static final class LoginSuccessProtoMsg extends
                    com.google.protobuf.GeneratedMessage implements
                    LoginSuccessProtoMsgOrBuilder {
        // Use LoginSuccessProtoMsg.newBuilder() to construct.
        private LoginSuccessProtoMsg(Builder builder) {
            super(builder);
        }

        private LoginSuccessProtoMsg(boolean noInit) {
        }

        private static final LoginSuccessProtoMsg defaultInstance;

        public static LoginSuccessProtoMsg getDefaultInstance() {
            return defaultInstance;
        }

        public LoginSuccessProtoMsg getDefaultInstanceForType() {
            return defaultInstance;
        }

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return com.road.arpg.module.misc.protobuff.LoginSuccessProto.internal_static_com_road_arpg_module_common_command_proto_LoginSuccessProtoMsg_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
            return com.road.arpg.module.misc.protobuff.LoginSuccessProto.internal_static_com_road_arpg_module_common_command_proto_LoginSuccessProtoMsg_fieldAccessorTable;
        }

        private int bitField0_;
        // required int64 playerID = 1;
        public static final int PLAYERID_FIELD_NUMBER = 1;
        private long playerID_;

        public boolean hasPlayerID() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        public long getPlayerID() {
            return playerID_;
        }

        private void initFields() {
            playerID_ = 0L;
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized != -1)
                return isInitialized == 1;

            if (!hasPlayerID()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeInt64(1, playerID_);
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1)
                return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream.computeInt64Size(
                                1, playerID_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @java.lang.Override
        protected java.lang.Object writeReplace()
                        throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static com.road.arpg.module.misc.protobuff.LoginSuccessProto.LoginSuccessProtoMsg parseFrom(
                        com.google.protobuf.ByteString data)
                        throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }

        public static com.road.arpg.module.misc.protobuff.LoginSuccessProto.LoginSuccessProtoMsg parseFrom(
                        com.google.protobuf.ByteString data,
                        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                            .buildParsed();
        }

        public static com.road.arpg.module.misc.protobuff.LoginSuccessProto.LoginSuccessProtoMsg parseFrom(
                        byte[] data)
                        throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }

        public static com.road.arpg.module.misc.protobuff.LoginSuccessProto.LoginSuccessProtoMsg parseFrom(
                        byte[] data,
                        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                            .buildParsed();
        }

        public static com.road.arpg.module.misc.protobuff.LoginSuccessProto.LoginSuccessProtoMsg parseFrom(
                        java.io.InputStream input) throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }

        public static com.road.arpg.module.misc.protobuff.LoginSuccessProto.LoginSuccessProtoMsg parseFrom(
                        java.io.InputStream input,
                        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                            .buildParsed();
        }

        public static com.road.arpg.module.misc.protobuff.LoginSuccessProto.LoginSuccessProtoMsg parseDelimitedFrom(
                        java.io.InputStream input) throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }

        public static com.road.arpg.module.misc.protobuff.LoginSuccessProto.LoginSuccessProtoMsg parseDelimitedFrom(
                        java.io.InputStream input,
                        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }

        public static com.road.arpg.module.misc.protobuff.LoginSuccessProto.LoginSuccessProtoMsg parseFrom(
                        com.google.protobuf.CodedInputStream input)
                        throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }

        public static com.road.arpg.module.misc.protobuff.LoginSuccessProto.LoginSuccessProtoMsg parseFrom(
                        com.google.protobuf.CodedInputStream input,
                        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                            .buildParsed();
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(
                        com.road.arpg.module.misc.protobuff.LoginSuccessProto.LoginSuccessProtoMsg prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        public static final class Builder extends
                        com.google.protobuf.GeneratedMessage.Builder<Builder>
                        implements
                        com.road.arpg.module.misc.protobuff.LoginSuccessProto.LoginSuccessProtoMsgOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return com.road.arpg.module.misc.protobuff.LoginSuccessProto.internal_static_com_road_arpg_module_common_command_proto_LoginSuccessProtoMsg_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
                return com.road.arpg.module.misc.protobuff.LoginSuccessProto.internal_static_com_road_arpg_module_common_command_proto_LoginSuccessProtoMsg_fieldAccessorTable;
            }

            // Construct using com.road.arpg.module.common.protobuff.LoginSuccessProto.LoginSuccessProtoMsg.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                playerID_ = 0L;
                bitField0_ = (bitField0_ & ~0x00000001);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                return com.road.arpg.module.misc.protobuff.LoginSuccessProto.LoginSuccessProtoMsg
                                .getDescriptor();
            }

            public com.road.arpg.module.misc.protobuff.LoginSuccessProto.LoginSuccessProtoMsg getDefaultInstanceForType() {
                return com.road.arpg.module.misc.protobuff.LoginSuccessProto.LoginSuccessProtoMsg
                                .getDefaultInstance();
            }

            public com.road.arpg.module.misc.protobuff.LoginSuccessProto.LoginSuccessProtoMsg build() {
                com.road.arpg.module.misc.protobuff.LoginSuccessProto.LoginSuccessProtoMsg result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            private com.road.arpg.module.misc.protobuff.LoginSuccessProto.LoginSuccessProtoMsg buildParsed()
                            throws com.google.protobuf.InvalidProtocolBufferException {
                com.road.arpg.module.misc.protobuff.LoginSuccessProto.LoginSuccessProtoMsg result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result)
                                    .asInvalidProtocolBufferException();
                }
                return result;
            }

            public com.road.arpg.module.misc.protobuff.LoginSuccessProto.LoginSuccessProtoMsg buildPartial() {
                com.road.arpg.module.misc.protobuff.LoginSuccessProto.LoginSuccessProtoMsg result = new com.road.arpg.module.misc.protobuff.LoginSuccessProto.LoginSuccessProtoMsg(
                                this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.playerID_ = playerID_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.road.arpg.module.misc.protobuff.LoginSuccessProto.LoginSuccessProtoMsg) {
                    return mergeFrom((com.road.arpg.module.misc.protobuff.LoginSuccessProto.LoginSuccessProtoMsg) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(
                            com.road.arpg.module.misc.protobuff.LoginSuccessProto.LoginSuccessProtoMsg other) {
                if (other == com.road.arpg.module.misc.protobuff.LoginSuccessProto.LoginSuccessProtoMsg
                                .getDefaultInstance())
                    return this;
                if (other.hasPlayerID()) {
                    setPlayerID(other.getPlayerID());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                if (!hasPlayerID()) {

                    return false;
                }
                return true;
            }

            public Builder mergeFrom(
                            com.google.protobuf.CodedInputStream input,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws java.io.IOException {
                com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
                                .newBuilder(this.getUnknownFields());
                while (true) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            this.setUnknownFields(unknownFields.build());
                            onChanged();
                            return this;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                            extensionRegistry, tag)) {
                                this.setUnknownFields(unknownFields.build());
                                onChanged();
                                return this;
                            }
                            break;
                        }
                        case 8: {
                            bitField0_ |= 0x00000001;
                            playerID_ = input.readInt64();
                            break;
                        }
                    }
                }
            }

            private int bitField0_;

            // required int64 playerID = 1;
            private long playerID_;

            public boolean hasPlayerID() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            public long getPlayerID() {
                return playerID_;
            }

            public Builder setPlayerID(long value) {
                bitField0_ |= 0x00000001;
                playerID_ = value;
                onChanged();
                return this;
            }

            public Builder clearPlayerID() {
                bitField0_ = (bitField0_ & ~0x00000001);
                playerID_ = 0L;
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:com.road.arpg.module.common.command.proto.LoginSuccessProtoMsg)
        }

        static {
            defaultInstance = new LoginSuccessProtoMsg(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:com.road.arpg.module.common.command.proto.LoginSuccessProtoMsg)
    }

    private static com.google.protobuf.Descriptors.Descriptor internal_static_com_road_arpg_module_common_command_proto_LoginSuccessProtoMsg_descriptor;
    private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_com_road_arpg_module_common_command_proto_LoginSuccessProtoMsg_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
    static {
        java.lang.String[] descriptorData = { "\n\032LoginSuccessProtoMsg.proto\022)com.road.a"
                        + "rpg.module.common.command.proto\"(\n\024Login"
                        + "SuccessProtoMsg\022\020\n\010playerID\030\001 \002(\003B;\n&com"
                        + ".road.arpg.module.common.command.pbB\021Log"
                        + "inSuccessProto" };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
            public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                descriptor = root;
                internal_static_com_road_arpg_module_common_command_proto_LoginSuccessProtoMsg_descriptor = getDescriptor()
                                .getMessageTypes().get(0);
                internal_static_com_road_arpg_module_common_command_proto_LoginSuccessProtoMsg_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                                internal_static_com_road_arpg_module_common_command_proto_LoginSuccessProtoMsg_descriptor,
                                new java.lang.String[] { "PlayerID", },
                                com.road.arpg.module.misc.protobuff.LoginSuccessProto.LoginSuccessProtoMsg.class,
                                com.road.arpg.module.misc.protobuff.LoginSuccessProto.LoginSuccessProtoMsg.Builder.class);
                return null;
            }
        };
        com.google.protobuf.Descriptors.FileDescriptor
                        .internalBuildGeneratedFileFrom(
                                        descriptorData,
                                        new com.google.protobuf.Descriptors.FileDescriptor[] {},
                                        assigner);
    }

    // @@protoc_insertion_point(outer_class_scope)
}
